Add trace of the error when debug verbosity
phpmd/phpmd pull request #1023
Opened 2023-08-20 14:17 UTC by kylekatarnls

Type: feature
Breaking change: no

- ``--error-file`` - send errors (other than reported violations) output to a file; default to `STDERR`

Allow to record error in a file (consistently with what is possible for report now with `--report-file`)

Handle deprecation and error consistently.

Show error stack trace when using debug verbosity.

2023-08-20 15:39 UTC, AJenbo approved these changes

2023-08-20 18:24 UTC, kylekatarnls commented
@ravage84 Would you mind to update the required jobs?

Renaming `PX.Y` => `Tests / PHP X.Y` for clarity and consistency with PDepend.

And extend range up to PHP version 8.3?

2023-08-20 20:45 UTC, AJenbo submitted a review, later dismissed

2023-08-20 21:21 UTC, AJenbo approved these changes
On a side note i think assert regex was removed in recent version, but i might be remembering wrong.

2023-08-20 21:36 UTC, kylekatarnls commented
> On a side note i think assert regex was removed in recent version, but i might be remembering wrong.

Yes, but the new method name is not available in the super-old version we need to use to support PHP 5.3 😢

2023-08-20 21:40 UTC, AJenbo commented
Hm the other main project I'm working with builds natively for 1987 Amiga and 2022 Android, I'm starting to question my life decisions.

2023-08-21 09:38 UTC, AJenbo approved these changes

2023-08-21 10:57 UTC, ravage84 requested changes

2023-08-21 10:57 UTC, ravage84 commented on src/site/rst/documentation/index.rst
> +  - ``--error-file`` - send errors (other than reported violations) output to a file; default to STDERR
```suggestion
  - ``--error-file`` - Sends errors (other than reported violations) output to a file; defaults to STDERR,
```

2023-08-21 10:57 UTC, ravage84 commented on src/test/php/bootstrap.php
> +if (class_exists('PHP_Token')) {
Let's add a short comment explaining why we that here.

2023-08-21 10:57 UTC, ravage84 commented on src/test/php/fix-php-compatibility.php
> +    __DIR__ . '/../../../vendor/phpunit/phpunit/src/Extensions/PhptTestCase.php' => array(
`__DIR__ . '/../../../vendor/`  or `__DIR__ . '/../../../vendor/phpunit/` could be put into a variable to make the lines shorter and more readable (focus on the more relevant part of the path.

2023-08-21 10:57 UTC, ravage84 commented on src/test/php/fix-php-compatibility.php
> +    __DIR__ . '/../../../vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php' => PHP_VERSION >= 7 ? array(
Brackets make it more readable.

```suggestion
    __DIR__ . '/../../../vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php' => (PHP_VERSION >= 7) ? array(
```

2023-08-21 10:57 UTC, ravage84 commented on src/test/php/fix-php-compatibility.php
> +    __DIR__ . '/../../../vendor/phpunit/php-code-coverage/src/CodeCoverage.php' => PHP_VERSION >= 7 ? array(
Brackets make it more readable.

```suggestion
    __DIR__ . '/../../../vendor/phpunit/php-code-coverage/src/CodeCoverage.php' => (PHP_VERSION >= 7) ? array(
```

2023-08-21 10:57 UTC, ravage84 commented on src/test/php/load-coverage-tokens.php
> +
Would be nice to have a short explanation of what this file is for beyond "load coverage tokens".

The why would be interesting.

```suggestion
<?php
/**
 * {WHAT WE DO} {WHY}
 */
```

2023-08-21 11:20 UTC, ravage84 commented
> @ravage84 Would you mind to update the required jobs?
> 
> Renaming `PX.Y` => `Tests / PHP X.Y` for clarity and consistency with PDepend.
> 
> And extend range up to PHP version 8.3?

Done. Should be active with the next builds.

2023-08-21 13:41 UTC, kylekatarnls commented on src/test/php/fix-php-compatibility.php
> +    __DIR__ . '/../../../vendor/phpunit/phpunit/src/Extensions/PhptTestCase.php' => array(
Advantage with static name over variable is that IDE is able to find the file on click.

2023-08-21 13:46 UTC, kylekatarnls commented on src/test/php/bootstrap.php
> +if (class_exists('PHP_Token')) {
```suggestion
/**
 * If t runs with coverage, it needs all the tokens to exist.
 * load-coverage-tokens.php will load the tokens that can be missing,
 * such as the PHP 8 tokens when running PHPUnit 5.
 */
if (class_exists('PHP_Token')) {
```

2023-08-21 16:14 UTC, AJenbo submitted a review, later dismissed

2023-08-21 16:29 UTC, ravage84 commented on src/test/php/bootstrap.php
> + * If t runs with coverage, it needs all the tokens to exist.
```suggestion
/*
 * If the test suite runs with coverage, it needs all the tokens to exist.
```

2023-08-21 16:30 UTC, ravage84 approved these changes

2023-08-21 16:42 UTC, merged