Allow option and value separated with equal
phpmd/phpmd pull request #1036
Opened 2023-09-27 14:56 UTC by kylekatarnls

Type: feature
Issue: Resolves #1035
Breaking change: yes

- Allow option and value separated with equal
- Implement argument separator `--`

It's a BC for users having file/directory names starting with `-` and passing them as argument of the `phpmd` command.

If this change is merged, they will see an error asking them add `--` in their command line to explicitly separate options from arguments.

2023-10-04 21:08 UTC, AJenbo submitted a review, later dismissed

2023-10-05 13:28 UTC, ravage84 requested changes
Looks generally good. Thank you.

2023-10-05 13:28 UTC, ravage84 commented on README.rst
> +  is equivalent to the previous one: ::
```suggestion
```suggestion
  Options can be before or after arguments. They can be separated from their value either with a space or an equal (``=``) sign.
  Thus, the following syntax is equivalent to the previous one: ::
```

https://dictionary.cambridge.org/dictionary/english/separate

2023-10-05 13:28 UTC, ravage84 commented on README.rst
> +    phpmd --reportfile phpmd.xml --suffixes php,phtml -- -foo/Folder xml codesize
Wouldn't it be generally advisable to use double quotes?

2023-10-05 13:28 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/CommandLineOptions.php
> +            '--: Explicit argument separator: anything after -- will be read as an argument even if' .
```suggestion
            '--: Explicit argument separator: Anything after "--" will be read as an argument even if' .
```

2023-10-05 13:28 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/CommandLineOptions.php
> +    private function refuseValue(array $equalChunk)
An explaining doc block would be nice.
What is meant with an "equalChunk"?

2023-10-05 13:28 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/CommandLineOptions.php
> +            throw new InvalidArgumentException($equalChunk[0] . ' option does not accept value');
```suggestion
            throw new InvalidArgumentException($equalChunk[0] . ' option does not accept a value');
```

2023-10-05 13:28 UTC, ravage84 commented on src/main/php/PHPMD/Utility/ArgumentsValidator.php
> +    public function validate($name, $value)
A doc block explaining the special cases would be nice.

2023-10-05 13:28 UTC, ravage84 commented on src/main/php/PHPMD/Utility/ArgumentsValidator.php
> +    private $arguments;
```suggestion
    /** @var bool */
    private $hasImplicitArguments;
    
    /** @var string[] */
    private $originalArguments;
    
    /** @var string[] */
    private $arguments;
```

2023-10-05 17:08 UTC, kylekatarnls commented on README.rst
> +    phpmd --reportfile phpmd.xml --suffixes php,phtml -- -foo/Folder xml codesize
Hum, it would be automatically supported with space syntax, but I think we'd need to decode it to get it to work after equal sign

2023-10-05 19:43 UTC, kylekatarnls commented on README.rst
> +    phpmd --reportfile phpmd.xml --suffixes php,phtml -- -foo/Folder xml codesize
Cool, I was wrong, sending `--suffixes="php,html"` to the CLI generates `--suffixes=php,html` in `$argv` 👌

2023-10-06 13:53 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/CommandLineOptions.php
> +     * return string|null
```suggestion
     * @return string|null
```

2023-10-06 13:54 UTC, ravage84 approved these changes

2023-10-06 15:07 UTC, merged