Implement LongMethodName
phpmd/phpmd pull request #1045
Opened 2023-11-28 19:40 UTC by kylekatarnls

Type: feature
Issue: Resolves Fix #486
Breaking change: no

2023-12-01 15:19 UTC, ravage84 requested changes
Thank you very much for the new rule.

Reviewed code-only, didn't test it.

2023-12-01 15:19 UTC, ravage84 commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +    public static function fromRule(AbstractRule $rule, $propertyName = 'exceptions')
I would move these up just below the constructor as they belong to the construction of the instance.

2023-12-01 15:19 UTC, ravage84 commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +class ExceptionProperty
This is quite a lot of code to replace a few lines previously. Not sure what to feel about it...

2023-12-01 15:19 UTC, ravage84 commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +    public function flip()
Isn't there any less technical name to express what we actually want to achieve or what we actually get back from this method?

Also, not having doc blocks, doesn't help either. 😞

2023-12-01 15:19 UTC, ravage84 commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +                return trim($className, " \t\n\r\0\x0B\\");
Is it really always class names? A more general name would probably a better fit, here.

2023-12-01 22:42 UTC, kylekatarnls commented on src/main/php/PHPMD/Rule/CleanCode/BooleanArgumentFlag.php
> +     *              an uniformized set of tools to handle the list of exceptions for a rule.
Not without breaking change, for the very reason that the return value is sometimes flipped sometimes not, see #982 we can make BC on next major and make it consistent by returning/storing a `ExceptionProperty` instance instead of the array and so we could lazily calculate the array JIT before it's actually needed, and use the needed structure according to the current check (pattern match, exact match, with or without trim).

2023-12-01 22:43 UTC, kylekatarnls commented on src/main/php/PHPMD/Rule/Naming/LongMethodName.php
> +     * length.
copy-paste from ShortMethodName, so it's also wrong in the current PHPDoc of this rule. :(

2023-12-01 22:48 UTC, kylekatarnls commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +    public function flip()
array_flip is a micro-optimization so index and isset() can be used instead of in_array(). However if we plan to support pattern everywhere we allow exceptions, then we would no longer need it in next major version.

2023-12-02 19:08 UTC, kylekatarnls commented on .github/workflows/tests.yml
> +        php: [5.3, 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
Extracted #1047

2023-12-02 19:28 UTC, kylekatarnls commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +class ExceptionProperty
This will make `getExceptionList()` to disappear completely in the next version and we can simply make `exceptions` available and working the same way for all the rule.

So on the next version it's more feature with way less (redundant) code.

2023-12-02 19:29 UTC, kylekatarnls commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +class ExceptionProperty
And introduce it now creates an easier step for people who created custom routes to prepare for upgrade.

2023-12-03 10:32 UTC, kylekatarnls commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +class ExceptionProperty
It would need more discussion as it's a bit more opinionated but other types of config could also be shared so to make them also working the same way across different rules and auto-discoverable and auto-documented.

For instance with attributes (but would need to drop PHP <= 7):

```php
class LongMethodName extends AbstractRule
{
  #[ConfigProperty(description: 'Comma-separated list of exceptions')]
  protected ExceptionProperty $exceptions;

  #[ConfigProperty(description: 'Maximum length for a method or function name')]
  protected Threshold $maximum;
}
``` 

Without dropping PHP version, it can be dependency-injection:
```php
class LongMethodName extends AbstractRule
{
  public function __construct(
    /** Comma-separated list of exceptions */
    ExceptionProperty $exceptions,

    /** Maximum length for a method or function name */
    Threshold $maximum,
  ) {
  }
}
```

2023-12-10 20:31 UTC, kylekatarnls commented on src/main/resources/rulesets/naming.xml
> +            <property name="maximum" description="Maximum length for a method or function name" value="20"/>
Taking a look at https://github.com/phpmd/phpmd/actions/runs/7159958473/job/19493792510?pr=1045#step:9:1769

I guess 20 might be a little short for a default value.

2024-01-09 21:39 UTC, kylekatarnls commented on src/main/php/PHPMD/Utility/ExceptionProperty.php
> +     * @return list<string>
`list` is now supported for years by PHPStorm, Plsam, PHPStan and Phan, it adds an interesting precision that keys of an `array $value` are strictly equal to `range(0, count($value)  -1)` (I.E. being ordered integer sequence starting at 0, see [array_is_list](https://www.php.net/manual/en/function.array-is-list)). Such as the result of `explode`, `array_values`, `array_keys`.

IMO giving the benefit to the majority of tools who support it worth to drop other tools supports (which should fallback  if they don't know how to read the annotation: to `array` if the return type is specified, else to `mixed`).

2026-05-10 22:53 UTC, AJenbo approved these changes

2026-05-10 22:53 UTC, merged