Convert consts to enums
phpmd/phpmd pull request #1154
Opened 2024-05-12 15:56 UTC by AJenbo

Type: refactoring  
Breaking change: yes

Converted the consts that where better suited as enums to such.

2024-05-12 23:59 UTC, ravage84 requested changes

2024-05-12 23:59 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/ExitCode.php
> +    case Error = 3;
It would be nice to have som doc blocks explaining the specifics a bit mroe.

Can these cases be of mixed state? May be some can.

Can these exit codes be manipulated through some CLI option, may be?

2024-05-12 23:59 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/ExitCode.php
> + * Exit codes used by the phpmd command line tool.
```suggestion
 * Exit codes used by the PHPMD command line tool.
```

2024-05-12 23:59 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/CommandLineOptions.php
> +                    if ($strategy === 'timestamp') {
Why is here a literal used?

2024-05-13 00:40 UTC, AJenbo commented on src/main/php/PHPMD/TextUI/CommandLineOptions.php
> +                    if ($strategy === 'timestamp') {
This is a string coming from the CLI input, we need to map it to the enum at some point and this was the earliest point I could find.

2024-05-13 00:42 UTC, AJenbo commented on src/main/php/PHPMD/TextUI/ExitCode.php
> +    case Error = 3;
I just moved them, I don't really know the answer to any of this :shrug: 

> Can these cases be of mixed state? May be some can.

No, you cannot combine multiple enums.

2024-05-13 18:06 UTC, AJenbo commented on src/main/php/PHPMD/TextUI/CommandLineOptions.php
> +                    if ($strategy === 'timestamp') {
Making it backed feels like the better option.

content is the default

2024-05-14 16:20 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/ExitCode.php
> +    /** When no exception was thrown, no violation was found and no error occured */
```suggestion
    /** When no exception was thrown, no violation was found and no error occurred */
```

2024-05-14 16:21 UTC, ravage84 approved these changes

2024-05-14 16:22 UTC, merged

2024-05-14 16:30 UTC, AJenbo commented
Thanks :)