[3.x] Add "--xdebug" CLI option to enabled Xdebug
phpmd/phpmd pull request #1158
Opened 2024-05-15 23:25 UTC by ravage84

Type: Feature
Issue: Resolves None
Breaking change: No

Inspired by https://dev.to/serendipityhq/how-to-debug-any-symfony-command-simply-passing-x-214o

This could easily be a feature of [composer/xdebug-handler](https://github.com/composer/xdebug-handler) itself, if they would want to.

2024-05-15 23:34 UTC, AJenbo commented on src/main/php/PHPMD/TextUI/XdebugOptionHandler.php
> +                unset($command[$configKey]);
```suggestion
                unset($command[$configKey + 1], $command[$configKey]);
```

2024-05-15 23:37 UTC, AJenbo commented on src/main/php/PHPMD/TextUI/XdebugOptionHandler.php
> +        parent::restart($command);
```suggestion
        if ($command) {
                parent::restart($command);
        }
```

2024-05-15 23:42 UTC, AJenbo commented
> This could easily be a feature of [composer/xdebug-handler](https://github.com/composer/xdebug-handler) itself, if they would want to.

Did you propose the change upstream?

2024-05-15 23:50 UTC, ravage84 commented
> Did you propose the change upstream?

Not yet

2024-05-15 23:55 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/XdebugOptionHandler.php
> +                unset($command[$configKey]);
I find it a tad bit more readable like before.

Or how about this?

```suggestion
                unset(
                    $command[$configKey + 1],
                    $command[$configKey]
                );
```

2024-05-15 23:58 UTC, ravage84 commented on src/main/php/PHPMD/TextUI/XdebugOptionHandler.php
> +                parent::restart($command);
```suggestion
            parent::restart($command);
```

2024-05-16 00:41 UTC, AJenbo approved these changes, later dismissed
just don't forget to remove it if they accept it upstream :D

2024-06-10 09:38 UTC, kylekatarnls submitted a review, later dismissed

2024-06-10 10:16 UTC, kylekatarnls commented on src/main/php/PHPMD/TextUI/XdebugOptionHandler.php
> +     * Rebuilds the run command with Xdebug enabled, instead, if CLI option "--xdebug" is used
This will help phpstan to know precisely what is the type of this array and so not to assume the key can be string:
```suggestion
     * Rebuilds the run command with Xdebug enabled, instead, if CLI option "--xdebug" is used.
     *
     * @param list<string> $command
```

2024-06-10 10:17 UTC, kylekatarnls approved these changes

2024-06-10 10:21 UTC, kylekatarnls requested changes
All good, we just need a unit test to cover src/main/php/PHPMD/TextUI/XdebugOptionHandler.php

2026-05-10 02:17 UTC, AJenbo approved these changes
Rebased and tests added

2026-05-10 02:18 UTC, merged