Conditional statements without logic should be avoided
phpmd/phpmd pull request #485
Opened 2017-06-05 22:04 UTC by eeree

This provides a functionality to signal `if/elseif` statements that have no logic. Example:

```
if (true) {
  // ...
} elseif ('foo' == null) {
  // ...
}
```

2017-06-06 01:36 UTC, ravage84 requested changes
Looks quite good.

2017-06-06 01:36 UTC, ravage84 commented on src/site/rst/rules/index.rst
> +- `IfStatementAssignment`__: Having if conditions without any logic should be avoided. It usually tells us, that we are dealing with development code fragment, debug data, etc.
You exchanged the texts here.

2017-06-06 01:36 UTC, ravage84 commented on src/main/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogic.php
> + * contains any logic. Statements that always
contain

2017-06-06 01:36 UTC, ravage84 commented on src/main/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogic.php
> +    private $positives = array(
Doc block missing.

2017-06-06 01:36 UTC, ravage84 commented on src/main/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogic.php
> +     * This method checks if method/function has if clauses
"if a given"

2017-06-06 01:36 UTC, ravage84 commented on src/main/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogic.php
> +     * that use assignment instead of comparison.
shouldn't check for "statements without logic"?

2017-06-06 01:36 UTC, ravage84 commented on src/main/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogic.php
> +        $ifStatements = $node->findChildrenOfType('IfStatement');
We use this one and the one below the second time... Thinking about extracting them into a specific function...

2017-06-06 01:36 UTC, ravage84 commented on src/main/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogic.php
> +                    if (!in_array(get_class($child), $this->positives)) {
Extract that to a separate function.

2017-06-06 01:36 UTC, ravage84 commented on src/main/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogic.php
> +            if ($violating) {
I wonder if we can write this in a cleaner way...

2017-06-06 01:36 UTC, ravage84 commented on src/main/resources/rulesets/cleancode.xml
> +          message="Unneeded if statement on line '{0}' in method '{1}'."
"Uneeded" is very general. Can we be more specific?

2017-06-06 01:36 UTC, ravage84 commented on src/test/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogicTest.php
> + * @package PHPMD\Rule\CleanCode
Remove package.

2017-06-06 01:36 UTC, ravage84 commented on src/test/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogicTest.php
> + * Class IfStatementWithoutLogicTest
If Statement Without Logic Test

2017-06-06 01:36 UTC, ravage84 commented on src/test/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToValidIfs.php
> +    if (~true | $xyz or (50 % $baz) >> 1 << 1 | 'foo' ^ /** ignore */ $foo) {
Nice!

2017-06-06 01:36 UTC, ravage84 commented on src/test/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToClasses.php
> +        if (array()) {
This one is arguable.

2017-06-06 01:36 UTC, ravage84 commented on src/test/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToElseIfCases.php
> +        // trigger violation
Make it a multi line comment for better visibility.

2017-06-06 01:36 UTC, ravage84 commented on src/test/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToElseIfCases.php
> +        // don't trigger
Make it a multi line comment for better visibility.

2017-06-06 01:36 UTC, ravage84 commented on src/test/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogicTest.php
> +     * 11 conditions should trigger violation
In one line, with comma.

2017-06-06 01:36 UTC, ravage84 commented on src/test/php/PHPMD/Rule/CleanCode/IfStatementWithoutLogicTest.php
> +     * 8 conditions should trigger violation
In one line, with comma.

2017-06-06 01:36 UTC, ravage84 commented on src/test/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToNestedIfs.php
> +        // trigger violation
Make it a multi line comment for better visibility.

2017-06-06 01:36 UTC, ravage84 commented on src/test/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToNestedIfs.php
> +        // don't trigger
Make it a multi line comment for better visibility.

2017-06-06 01:47 UTC, ravage84 commented
I wonder if we should extend this rule to all or better said most conditionals.
How about including:
- [Ternary](http://php.net/manual/en/language.operators.comparison.php#language.operators.comparison.ternary)
- [for](http://php.net/manual/en/control-structures.for.php)
- [while](http://php.net/manual/en/control-structures.while.php)
- [switch](http://php.net/manual/en/control-structures.switch.php)

Same could apply for ``IfStatementAssignment`` by the way.

2017-06-06 18:34 UTC, ravage84 commented on .stickler.yml
> +      - 'Squiz.Classes.ValidClassName'
Nope, this rule is fine by itself. It's just not relevant for test resource files. But let's change that in a separate PR. Please revert. I'll ignore the issues Stickler nags about 😼

2017-06-06 18:39 UTC, eeree commented on .stickler.yml
> +      - 'Squiz.Classes.ValidClassName'
Do you even sleep?

2017-06-06 18:40 UTC, ravage84 commented on .stickler.yml
> +      - 'Squiz.Classes.ValidClassName'
🤣 Get in touch with me by Skype. I'll explain.

2017-06-15 11:38 UTC, ravage84 commented
Needs rebasing plus requested changes. Thanks

2019-08-17 19:51 UTC, tvbeek commented
@eeree Do you have the possibility to rebase and update with the feedback from @ravage84 ? Please say it if it isn't possible because then someone else need to take a look.

2019-10-19 10:05 UTC, kylekatarnls requested changes

2019-10-19 10:05 UTC, kylekatarnls commented on src/site/rst/rules/cleancode.rst
>  Since: PHPMD 2.7.0
Will be at least 2.9.0

2020-05-06 18:40 UTC, ravage84 commented
@eeree are you still intersted in pursuing this?

2022-04-12 21:18 UTC, tvbeek commented
@eeree @ravage84 @kylekatarnls If I'm correctly this PR need a rebase and update for the version number. After that (and verifying that it didn't result in any problem) it could be merged. Is that correct?

2026-05-10 02:38 UTC, AJenbo commented on public/rst/rules/cleancode.rst
> +Since: PHPMD 2.7.0
```suggestion
Since: PHPMD 3.0.0
```

2026-05-10 02:39 UTC, AJenbo commented on .stickler.yml
> +      - 'Squiz.Classes.ValidClassName'
```suggestion
```

2026-05-10 02:40 UTC, AJenbo commented on tests/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToNestedIfs.php
> +        // don't trigger
```suggestion
        /** don't trigger */
```

2026-05-10 02:41 UTC, AJenbo commented on tests/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToNestedIfs.php
> +        // trigger violation
```suggestion
        /** trigger violation */
```

2026-05-10 21:28 UTC, AJenbo commented on tests/resources/files/Rule/CleanCode/IfStatementWithoutLogic/testRuleNotAppliesToClasses.php
> +        if (array()) {
I'll just leave it as is, someone else can argue it :)

2026-05-10 21:29 UTC, AJenbo commented on rulesets/cleancode.xml
> +          message="Unneeded if statement on line '{0}' in method '{1}'."
I couldn't come up with anything better.

2026-05-10 21:32 UTC, AJenbo commented
<img width="1549" height="1124" alt="image" src="https://github.com/user-attachments/assets/c9bb6c12-d597-4675-9a65-ffa8ab3d36d0" />

2026-05-10 21:34 UTC, AJenbo approved these changes

2026-05-10 21:37 UTC, merged