Custom command line options for custom renderer
phpmd/phpmd pull request #543
Opened 2018-01-11 19:44 UTC by dnolbon

adds the ability to transmit custom command line options for custom renderer

For example:
`phpmd --custom-pretty-json 1 path-to-source JsonRenderer codesize,unusedcode,naming`

Then in custom renderer we can get these options in costructor and then use them in renderReport function, for example:
```
class JsonRenderer extends AbstractRenderer
{
    /**
     * Custom command line options
     *
     * @var array
     */
    protected $options = [];

    public function __construct($options)
    {
        $this->options = $options;
    }

    /**
     * This method will be called when the engine has finished the source analysis
     * phase.
     *
     * @param \PHPMD\Report $report
     * @return void
     */
    public function renderReport(Report $report)
    {
        ...
        $options = 0;
        if (isset($this->options['pretty-json']) && (int)$this->options['pretty-json'] === 1) {
            $options = JSON_PRETTY_PRINT;
        }
        ...
    }
}
```
Full example can see [here](https://github.com/dnolbon/phpmd-renderer)

2019-06-25 09:04 UTC, kylekatarnls approved these changes

2019-06-25 10:48 UTC, ravage84 requested changes
@dnolbon looks good. Could you please add documentation? This way this new feature actually gets discovered by other's.

Plus, I'm not sure "custom" is a good choice. If these options are for renderers, why not use something like ``--render-XYZ``?

2020-05-06 18:38 UTC, ravage84 commented
I still think since these optons are for renderers only, the CLI parameter should be named ``--render-options`` or something that line...

@dnolbon are you still interested in pursuing this?

2026-02-01 16:45 UTC, AJenbo commented
I think it would be better to allow custom renders to hook in to the argument configuration, this would allow them to be exposed on the help screen as well.

2026-02-01 16:45 UTC, closed without merging