Add ExceptionList property for LongParameterList
phpmd/phpmd pull request #559
Opened 2018-03-23 15:22 UTC by andrewwheal

I took inspiration/code from the [ShortVariable](https://github.com/phpmd/phpmd/blob/master/src/main/php/PHPMD/Rule/Naming/ShortVariable.php#L122) rule which already had an exception list property and added it to the LongParameterList rule.

2019-06-25 08:44 UTC, kylekatarnls submitted a review, later dismissed

2019-06-25 10:55 UTC, ravage84 requested changes
@andrewwheal thank you for your enhancement.
Please add some documentation. This way, other's will find this nice enhancement, too.

2019-06-25 10:55 UTC, ravage84 commented on src/main/php/PHPMD/Rule/Design/LongParameterList.php
> +
Remove white line to move these two related code parts together. As they belong toghether and do a special thing, they can be extracted into a separate protected method.

For example:

```` php
        if ($this->parameterIsInExceptionList()) {
            return;
        }
````

2019-06-25 13:10 UTC, MarkVaughn submitted a review, later dismissed

2020-05-06 18:39 UTC, ravage84 commented
@andrewwheal are you still intersted in pursuing this?

2026-05-10 01:28 UTC, AJenbo commented
Moved to https://github.com/phpmd/phpmd/pull/1295

2026-05-10 01:28 UTC, closed without merging