set rule properties in config file
phpmd/phpmd pull request #664
Opened 2019-08-14 07:56 UTC by tis-dm-webfactory

sorry for messing up the previous pull request - i closed it and created a new one.

add possibility to modify rule properties via config file without defining a completely new rule

something like this:

	<?xml version="1.0" encoding="UTF-8"?>
		<ruleset name="pcsg-generated-ruleset"
				 xmlns="http://pmd.sf.net/ruleset/1.0.0"
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 http://pmd.sf.net/ruleset_xml_schema.xsd"
				 xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd">
		<description>Created with the PHP Coding Standard Generator.
			http://edorian.github.com/php-coding-standard-generator/
		</description>
		
		<rule ref="rulesets/design.xml"/>
		<rule name="CouplingBetweenObjects">
			<properties>
				<property name="maximum" value="20"/>
			</properties>
		</rule>
	</ruleset>

2019-08-14 08:58 UTC, kylekatarnls commented
Hi thanks, I like this feature a lot. I fixed the PHP 5.3 compatibility in your PR (please pull the change). Could you now add a unit test for that?

And it would be perfect to add a note about this in https://github.com/phpmd/phpmd/blob/master/src/site/rst/documentation/creating-a-ruleset.rst

So other users will know this exists.

2019-08-14 10:29 UTC, tis-dm-webfactory commented
hi Kyle,

yeah sure - I've added two (simple) tests and also wrote a paragraph about how this feature works.
I've pushed it in our repo - if you need another pull request just let me know.

2019-08-14 11:22 UTC, kylekatarnls submitted a review, later dismissed
Very nice!

2019-08-21 14:30 UTC, MarkVaughn submitted a review, later dismissed
Noice

2019-08-21 14:43 UTC, kylekatarnls commented
@ravage84 A last word on this before merging?

2019-08-21 14:56 UTC, ravage84 requested changes
If I understand this PR correctly, it adds the possibility to overwrite the properties of rules without excluding them, once they are added through a rule set, correct?

2019-08-21 14:56 UTC, ravage84 commented on src/main/php/PHPMD/RuleSetFactory.php
> +     * modifyExistingRuleset
Please use an actual phrase, you can use the explanation two lines below.

2019-08-21 14:56 UTC, ravage84 commented on src/main/php/PHPMD/RuleSetFactory.php
> +        // find existing rule
A method like this often indicates that it is better to have a sub method with a self explanatory name (plus doc block).

2019-08-21 14:56 UTC, ravage84 commented on src/site/rst/documentation/creating-a-ruleset.rst
> +Changing properties in a rule set for multiple rules
Important words in titles can be written in capital letters.

2019-08-21 14:56 UTC, ravage84 commented on src/test/php/PHPMD/RuleSetFactoryTest.php
> +     * testCreateRuleSetsWithoutRuleReferenceThatOverwritesSettings
Please use full sentences. Otherwise this has no added benefit.

2019-08-21 14:56 UTC, ravage84 commented on src/test/php/PHPMD/RuleSetFactoryTest.php
> +     * testCreateRuleSetsWithoutRuleReferenceThatOverwritesSettingsButDoesntAddProperties
Please use full sentences. Otherwise this has no added benefit.

2019-08-21 14:56 UTC, ravage84 commented on src/test/resources/files/rulesets/refset5.xml
> +<ruleset name="Third Test RuleSet"
Fifth

2019-08-21 14:56 UTC, ravage84 commented on src/test/resources/files/rulesets/refset5.xml
> +    <description>First description...</description>
May be we can use the description to describe what is going on in this rule set file

2019-08-21 14:56 UTC, ravage84 commented on src/test/resources/files/rulesets/set3.xml
> +<ruleset name="Second Test RuleSet"
Third

2019-08-21 14:56 UTC, ravage84 commented on src/test/resources/files/rulesets/set3.xml
> +	<description>Second description...</description>
May be we can use the description to describe what is going on in this rule set file

2019-08-23 11:10 UTC, tis-dm-webfactory commented on src/main/php/PHPMD/RuleSetFactory.php
> +     * modifyExistingRuleset
I've change the comment, please see the latest update

2019-08-23 11:10 UTC, tis-dm-webfactory commented on src/main/php/PHPMD/RuleSetFactory.php
> +        // find existing rule
I've extracted searching for a rule to a method - please see latest commit

2019-08-23 11:11 UTC, tis-dm-webfactory commented on src/site/rst/documentation/creating-a-ruleset.rst
> +Changing properties in a rule set for multiple rules
I'm sorry, but I can't see anything wrong here. The titles look similar throughout the whole file ;-)

2019-08-23 11:11 UTC, tis-dm-webfactory commented on src/test/php/PHPMD/RuleSetFactoryTest.php
> +     * testCreateRuleSetsWithoutRuleReferenceThatOverwritesSettings
I've change the comment, please see the latest update

2019-08-23 11:11 UTC, tis-dm-webfactory commented on src/test/php/PHPMD/RuleSetFactoryTest.php
> +     * testCreateRuleSetsWithoutRuleReferenceThatOverwritesSettingsButDoesntAddProperties
I've change the comment, please see the latest update

2019-08-26 06:20 UTC, tis-dm-webfactory commented
> If I understand this PR correctly, it adds the possibility to overwrite the properties of rules without excluding them, once they are added through a rule set, correct?

absolutely correct ;-)

2019-09-17 06:49 UTC, tis-dm-webfactory commented
@ravage84
@MarkVaughn 
@kylekatarnls 
do you need any more changes? there's been no more comments since my last update.

2019-09-17 07:31 UTC, kylekatarnls submitted a review, later dismissed
It's alright for me.

2019-09-17 07:31 UTC, kylekatarnls commented on src/site/rst/documentation/creating-a-ruleset.rst
> +Changing properties in a rule set for multiple rules
Good for me.

2020-04-29 08:45 UTC, tvbeek submitted a review, later dismissed
Nice PR, this made it more easy to change the rules for your need.

Thanks

2020-04-29 20:28 UTC, MarkVaughn submitted a review, later dismissed

2020-05-06 17:24 UTC, ravage84 submitted a review, later dismissed
@tis-dm-webfactory thank you for your work. It won't take much to make this mergable.
Can you also please rebase it upon our current master?

2020-05-06 17:24 UTC, ravage84 commented on src/site/rst/documentation/creating-a-ruleset.rst
> +      <!--
The previous examples build upon the one example before them. Should we keep that narrative style?

2020-05-06 17:24 UTC, ravage84 commented on src/main/php/PHPMD/RuleSetFactory.php
> +        if ($className === '') {
The intend of this coude section could be communicated better. May be a comment is necessary?

2020-05-06 17:29 UTC, ravage84 commented
I think this PR resolves https://github.com/phpmd/phpmd/issues/39

2020-05-18 07:46 UTC, kylekatarnls submitted a review, later dismissed
What about merging and cleanup old documentation in an other PR?

2020-05-18 11:32 UTC, kylekatarnls submitted a review, later dismissed
I moved the early-return earlier in the method and pulled master.

Side note: It's a lot of commits now. I propose to squash this PR.

2020-05-18 22:37 UTC, ravage84 commented
@kylekatarnls 

> What about merging and cleanup old documentation in an other PR?

Can we address https://github.com/phpmd/phpmd/pull/664#discussion_r420938937 before doing so?

> Side note: It's a lot of commits now. I propose to squash this PR.

I agree.

2020-05-19 07:18 UTC, kylekatarnls commented on src/test/php/PHPMD/RuleSetFactoryTest.php
> +     * Check if properties are changed, but no additional properties are added to rules
This test is not useless, it fails on the current version of RuleSetFactory and it succeed with this change. I will update it to make it a bit more short and clear.

2020-05-19 07:19 UTC, kylekatarnls commented
Addressed https://github.com/phpmd/phpmd/pull/664/commits/8d296f83ed50e39c1fa796628a00c07f76f45061

If I well understand, this does not change the intent of the test.

2020-05-19 17:50 UTC, ravage84 commented
@kylekatarnls 

> Addressed [8d296f8](https://github.com/phpmd/phpmd/commit/8d296f83ed50e39c1fa796628a00c07f76f45061)
> 
> If I well understand, this does not change the intent of the test.

I figured it out:

The point of this test is that the property ``test`` in rule ``RuleThreeInFifthRuleSet`` from [src/test/resources/files/rulesets/refset5.xml](https://github.com/phpmd/phpmd/pull/664/files#diff-6ff82293398c390e7df1f1d334240c22R25) should not add this property to that rule as it didn't exist before in the original rule set [src/test/resources/files/rulesets/set3.xml](https://github.com/phpmd/phpmd/pull/664/files#diff-7405741fb106eec9cc487ac854275b28R36-R45).

The current test doesn't realy cover this as it would fail at the [first retrieval of the property](https://github.com/phpmd/phpmd/pull/664/files#diff-f7bef854eeb9f7fb07bbd08f2c75ec82R767) because [the names of the properties for the first two rules](https://github.com/phpmd/phpmd/pull/664/files#diff-6ff82293398c390e7df1f1d334240c22R15-R20) in the rule set are ``test1`` and ``test2`` and not ``test``.

To cover this case we either have to look at the full list of properties (which would also be a more stable test) or just fetch the third rule.

2020-05-23 11:15 UTC, kylekatarnls commented on src/site/rst/documentation/creating-a-ruleset.rst
> +We want to use the basic codesize ruleset, but change parameter values for
I'll remove the previous chapter.

2020-05-23 11:16 UTC, kylekatarnls commented on src/site/rst/documentation/creating-a-ruleset.rst
> +      <!--
I don't like neither. I will add some `if` and `for instance` to make it clear it's just an example.

2020-05-23 11:20 UTC, kylekatarnls commented on src/site/rst/documentation/creating-a-ruleset.rst
> +      <!--
In fact, it's used very widely, we should handle this in a next PR. And keep it consistent like it is for now.

2020-05-23 11:31 UTC, kylekatarnls commented on src/main/php/PHPMD/RuleSetFactory.php
> +    private function findRuleInRulesetByName(RuleSet $ruleSet, string $ruleName)
string type hint is not possible in PHP 5

2020-05-23 11:43 UTC, kylekatarnls commented on src/main/php/PHPMD/RuleSetFactory.php
> +        while ($rules->valid()) {
This is an iterator, it can be iterated simply using `foreach ($rulesSet as $rule)` with no calls to `->getRules()` `->valid()` `->current()` or `->next()`

2020-05-23 11:46 UTC, kylekatarnls requested changes
The feature is actually not compatible with PHP 5. The unit tests only pass because the test trigger 0 assertions in PHP 5.

2020-05-23 12:05 UTC, kylekatarnls commented
Actually the test does not perform any assertions neither in PHP 7 because the `array_key_exists($name, $expected)` is always `false`.

2020-05-23 12:17 UTC, kylekatarnls commented
I fixed the test to make it check what it intended to and sadly it fails (0 instead of 42 in test1 property).

2020-05-23 12:32 UTC, kylekatarnls commented on src/site/rst/documentation/creating-a-ruleset.rst
> +      <rule name="ExcessiveParameterList">
I would actually prefer that the rule would be inside the ` <rule ref="rulesets/codesize.xml">...</rule>`

2020-05-23 12:35 UTC, kylekatarnls commented
I checked, It's just a problem with the test. The feature works properly with the example given in the new documentation.

2020-05-23 12:49 UTC, kylekatarnls commented
Test fixed. It was a naming problem: RuleOneInThirdRuleSet instead of RuleOneInFifthRuleSet as it refers to the set3.xml.

2020-05-23 12:54 UTC, kylekatarnls submitted a review, later dismissed
Tests fixed.
https://travis-ci.org/github/phpmd/phpmd/builds/690347990

2020-05-23 12:56 UTC, kylekatarnls commented on src/site/rst/documentation/creating-a-ruleset.rst
> +      <rule name="ExcessiveParameterList">
After a second thinking, it's fine, we should not have the same rule name in 2 different rule-sets and it's easier for the user if he/she doesn't need to know the rule-set of every rule.

2020-05-23 17:53 UTC, MarkVaughn submitted a review, later dismissed

2022-04-12 21:11 UTC, tvbeek commented
@tis-dm-webfactory I'm realizing that this is an old PR. Are you able to rebase it to handle the conflicts and let it run the tests with the GitHub actions?

2026-05-12 08:07 UTC, AJenbo approved these changes

2026-05-12 08:09 UTC, merged

2026-05-12 08:10 UTC, AJenbo commented
Only 7 people had a hand in this PR