Add baseName key to report
phpmd/phpmd pull request #706
Opened 2019-12-07 12:52 UTC by ttomdewit

Type: (feature)  
Issue: Resolves #704
Breaking change: no

Explain what the PR does and also why. If you have parts you are not sure about, please explain. 

Please check this points before submitting your PR.
 - [ ] Add test to cover the changes you made on the code.
 - [ ] If you have a change on the documentation, please link to the page that you change.
 - [ ] If you add a new feature please update the documentation in the same PR.
 -  ~~If you really need to add a breaking change, explain why it is needed. Understand that this result in a lower change to get the PR accepted.~~
 - [ ] Any PR need 2 approvals before it get merged, sometimes this can take some time. Please be patient.

2019-12-07 14:23 UTC, kylekatarnls requested changes
The tests will need to cover `getBaseName` new method. Right now it does not because the violation class is mocked.

But if you have trouble, I can add them.

2019-12-08 10:54 UTC, ttomdewit reviewed
> The tests will need to cover `getBaseName` new method. Right now it does not because the violation class is mocked.
> 
> But if you have trouble, I can add them.

This I don't fully understand. Can you help?

2019-12-23 20:24 UTC, tvbeek commented on src/main/php/PHPMD/RuleViolation.php
> +    public function getBaseName()
That can be a good idea, but we need to take care that it means we also need to upper the minimum PDepend version for PHPMD. You can create a PR on PDepend, that means that we need to create a new release for that project before merging this PR.

2019-12-23 20:45 UTC, tvbeek commented
> 
> 
> > The tests will need to cover `getBaseName` new method. Right now it does not because the violation class is mocked.
> > But if you have trouble, I can add them.
> 
> This I don't fully understand. Can you help?

Because your addition on the getRuleViolationMock function in the src/test/php/PHPMD/AbstractTest.php class you mock the getBaseName method. That is useful for the other tests. But now your change on the src/test/php/PHPMD/Renderer/JSONRendererTest.php and the src/test/resources/files/renderer/json_renderer_expected.json doesn't really test the newly added method.

The most visible way to validate it is by running phpunit with the option `--coverage-html=path/to/coverage/dir`, then open index.html in path/to/coverage/dir (or what you choose) and navigate to the file that you changed. You will see that getBaseName from the RuleViolation isn't coveraged by the test.

2020-05-06 18:50 UTC, ravage84 commented
@ttomdewit are you still interested in pursuing this?

2020-05-06 19:15 UTC, ttomdewit commented
@ravage84 Yes, but I’m recovering from burnout and dealing with depression so I’m not able to commit to anything I’m afraid.

2020-05-06 19:25 UTC, ravage84 commented
@ttomdewit no worries. We can keep it open for you. Have a good recovery.

2026-05-12 08:25 UTC, AJenbo submitted a review, later dismissed

2026-05-12 08:28 UTC, AJenbo commented
@ttomdewit hope your doing well, I patched this one up so it can be part of 3.0.0

2026-05-12 08:29 UTC, AJenbo approved these changes

2026-05-12 08:30 UTC, merged