Fix #868: Option to ignore globally-namespaced classes from MissingImport
phpmd/phpmd pull request #869
Opened 2021-02-10 20:32 UTC by danepowell

Type: feature
Issue: Resolves #868
Breaking change: no

See #868 for motivation. Adds a property `ignore-global` to the MissingImport rule that will cause it to ignore classes in the global namespace (i.e. [classes that do not contain a backslash in their FQN](https://www.drupal.org/project/coder/issues/3120001)).

This still needs tests but I'd like maintainer approval and guidance before proceeding with that, since I'm a little intimidated by the unit test architecture. I don't know how to incorporate an optional flag into the test cases.

As an aside, kudos on maintaining a very well-organized and documented codebase, it was pretty easy to grok.

2021-02-11 08:43 UTC, tvbeek commented
@danepowell thanks for the PR. Maybe you already got an notification / email from the GitHub actions but there are failing test. If I take a quick look it is the result of not having a default value. Can you check check and update it? (Not having a default value that keeps the current logic should also make it a breaking change)

2021-02-11 21:28 UTC, danepowell commented
Thanks, I fixed the broken test and also added a test case for the new option.

2021-02-11 23:35 UTC, kylekatarnls commented on src/site/rst/rules/cleancode.rst
> +| ignore-global                     |               | Ignore classes in the global namespace                     |
```suggestion
| ignore-global                     |               | Ignore classes and interfaces in the global namespace      |
```

2021-02-27 19:58 UTC, tvbeek requested changes
I have a small request for change, just to make it more explicit. After that I think it is perfect.

2021-02-27 19:58 UTC, tvbeek commented on src/site/rst/rules/cleancode.rst
> +| ignore-global                     |               | Ignore classes and interfaces in the global namespace      |
```suggestion
| ignore-global                     |               | Ignore classes, interfaces and traits in the global namespace      |
```

I think after the comment from @kylekatarnls that it is good to make the description as complete as possible.

2021-03-10 20:14 UTC, tvbeek approved these changes

2021-03-10 20:14 UTC, merged

2021-03-10 20:15 UTC, tvbeek commented
Thanks for the PR