Add prefix removal for class names and variable names
phpmd/phpmd pull request #962
Opened 2022-06-15 22:14 UTC by JoshuaBehrens

Type: feature / documentation update
Issue: Adds prefix removal for variables and class names
Breaking change: no
Changed documentation pages:
- https://phpmd.org/rules/naming.html

My issue is for class names that need to follow a pattern. E.g. doctrine/migrations expect migration classes to have a prefix. Following a functional pattern should not count to a meaningful name limitation. phpmd does not support this yet.

As we also have a rule for variable names I thought about this change being useful there as well. I think about Hungarian notation name schemas. I don't use them and I support statements that they are dated but it is a thing. In addition I can imagine similar situations for properties like patterns in the class name situation. Sooo I just added it as well.

Please check this points before submitting your PR.
 - [x] Add test to cover the changes you made on the code.
 - [x] If you have a change on the documentation, please link to the page that you change. 
 - [x] If you add a new feature please update the documentation in the same PR.
 - [x] If you really need to add a breaking change, explain why it is needed. Understand that this result in a lower change to get the PR accepted.\
\
I made it non-breaking 😃 
 - [x] Any PR need 2 approvals before it get merged, sometimes this can take some time. Please be patient.
  
## Adding a New Rule Property

- [x] Add the new property to rule set XML, e.g. ``src/main/resources/rulesets/naming.xml``
- [x] Add documentation for the new property, e.g. ``src/site/rst/rules/naming.rst``
- [x] Implement new property in rule, e.g. ``src/main/php/PHPMD/Rule/Naming/LongVariable.php``
- [x] Cover cases for the new property in rule test, e.g. ``src/test/php/PHPMD/Rule/Naming/LongVariableTest.php``
  - [x] Cover the case when the new property is not set and the rule *should not* apply
  - [ ] Cover the case when the new property is not set and the rule *should* apply
  - [ ] Cover case when the new property is set and the rule *should not* apply
  - [x] Cover case when the new property is set and the rule *should* apply
  - [ ] Cover edge cases of the new property, if any

## Comment

I admit I did not look out for contribution guides. I just did. Reviewing your checklist here I think I already covered most of the parts. As I shall be patient I can also later amend my tests. For now you can already get what I want to do and review my approach. I assume I did not match something and I have to adjust anyway 😅

2022-06-16 06:24 UTC, tvbeek commented
@JoshuaBehrens thanks for your PR. The first high over impression is that you did a good job. I have enabled the GitHub actions to run but now I see that they fail, can you take a look to it?

2022-06-16 08:01 UTC, JoshuaBehrens commented
Thank you for the quick feedback. I was not sure we are talking about that level of patience :D
Sure. I think I already saw the issue. Test fixture lookup by method name fails because I had some test method renaming going on.

2022-09-05 06:25 UTC, kylekatarnls requested changes
Just a test to fix and good to go.

2022-09-05 06:25 UTC, kylekatarnls commented on src/test/php/PHPMD/Utility/StringsTest.php
> +        static::assertSame(8, Strings::lengthWithoutSuffixes('FooUnitTest', array('Foo', 'Bar')));
This test is failing, but it's length without suffix so prefix being ignored sounds legit.

2022-09-05 09:09 UTC, JoshuaBehrens commented on src/test/php/PHPMD/Utility/StringsTest.php
> +        static::assertSame(8, Strings::lengthWithoutSuffixes('FooUnitTest', array('Foo', 'Bar')));
Thanks for bringing this back into my notifications. I will look into it

2022-09-10 12:10 UTC, kylekatarnls commented on src/test/php/PHPMD/Utility/StringsTest.php
> +        static::assertSame(8, Strings::lengthWithoutSuffixes('FooUnitTest', array('Foo', 'Bar')));
```suggestion
        static::assertSame(11, Strings::lengthWithoutSuffixes('FooUnitTest', array('Foo', 'Bar')));
        static::assertSame(8, Strings::lengthWithoutSuffixes('UnitTestFoo', array('Foo', 'Bar')));
```

2022-09-10 12:19 UTC, kylekatarnls commented on src/main/php/PHPMD/Utility/Strings.php
> +        rsort($subtractPrefixes, SORT_STRING);
I see the interest of taking the longest possible prefix but this is inconsistent with the behavior for suffix and also with documentation saying
> first matching prefix will be subtracted

2022-09-11 12:01 UTC, JoshuaBehrens commented on src/main/php/PHPMD/Utility/Strings.php
> +        rsort($subtractPrefixes, SORT_STRING);
Good check. I am fine with following the same rules suffixes. Less breaking changes :)

2022-09-11 12:42 UTC, kylekatarnls commented on src/main/php/PHPMD/Utility/Strings.php
> +        rsort($subtractPrefixes, SORT_STRING);
The `rsort` could be applied to both as defining `FooUnit` after `Foo` in prefix or `FooUnit` after `Unit` in suffix would have no effect. So I guess it's very unlikely to break anything for real life users. If so we just need to replace "first matching" with "longest matching" in documentation.

Both are equally fine for me. I just wish both to be harmonized and doc to reflect the behavior. 👌

2022-09-11 14:46 UTC, JoshuaBehrens commented on src/main/php/PHPMD/Utility/Strings.php
> +        rsort($subtractPrefixes, SORT_STRING);
Then I would go for the docs changes

2022-09-12 20:29 UTC, JoshuaBehrens commented on src/main/php/PHPMD/Utility/Strings.php
> +        rsort($subtractPrefixes, SORT_STRING);
Changed it :) anything else?

2022-09-13 21:09 UTC, kylekatarnls commented on src/main/php/PHPMD/Utility/Strings.php
> +        rsort($subtractPrefixes, SORT_STRING);
Sorry, now I see my explanation was ambiguous when re-reading it.

Both choosing first or longest would be OK. But main points are:
- suffixes and prefixes should apply the same option (either both select longest matching, i.e. are `rsort()` -ed, or both take the first)
- then RST and XML docs just need to tell what it is. BTW I think "longest, first" can be just "longest" as since it's sorted, the "first" no longer apply to the order in config + 2 different strings of the same length cannot be the prefix (or suffix) of 1 given string.

But don't worry, this is really good 🙏 , and will be there in 2.14.0, if you're not sure or don't have time, I'll make this minor last change.

2022-09-13 21:32 UTC, JoshuaBehrens commented on src/main/php/PHPMD/Utility/Strings.php
> +        rsort($subtractPrefixes, SORT_STRING);
I do have time right now :) in my recent commit I changed my prefix removal to just "longest" in all docs.

Ok, so when we want to have suffix and prefix handling identical and it is a minor increment (I assume you do semver), I must not change the way suffixes are handled right now and therefore make prefix removal go for first-match strategy like the suffixes.

Thank you for considering this for the next release. HYPE! :tada: 

When there are any plans for improvements for a 3.x release, I think this could need a breaking change on how to make the configuration, but I think this can be discussed outside of this PR :)

2022-09-13 21:59 UTC, JoshuaBehrens commented on src/main/php/PHPMD/Utility/Strings.php
> +        rsort($subtractPrefixes, SORT_STRING);
I fixed code style, removed the rsort and changed tests that found it, amend all docs. Did I miss sth?

2022-11-26 19:51 UTC, kylekatarnls approved these changes

2023-07-25 18:10 UTC, JoshuaBehrens commented
Is a rebase beneficial for this to get merged? :) I can do that if it helps

2023-07-25 18:15 UTC, AJenbo commented on src/main/php/PHPMD/Rule/Naming/LongVariable.php
> +            \ltrim($variableName, '$'),
Nit: I dont' think we normally name space functions
```suggestion
            ltrim($variableName, '$'),
```

2023-07-25 18:15 UTC, AJenbo approved these changes

2023-07-25 18:15 UTC, merged

2023-07-26 08:00 UTC, JoshuaBehrens commented
Thank you @AJenbo for taking care of the pull request :) love to contribute again. I have some more ideas