Add ExceptionList property for UnusedFormalParameter
phpmd/phpmd pull request #984
Opened 2022-09-23 19:26 UTC by PedroPMS

Type: feature

This PR add the exception property to the UnusedFormalParameter rule.

Some classes of some frameworks, such as Laravel ApiResource, uses some parameters that arent used by the method.

![image](https://user-images.githubusercontent.com/48099126/192042712-d859a7e9-f98d-4899-8a63-c03ddab0cb39.png)

2022-09-23 21:19 UTC, PedroPMS commented
> Isn't that then a fault with the class, correctly detected by PHPMD. and should be corrected instead of ignored?

Yeah, is a fault with the class, but the entire framework uses like this. So we can only ask for a fix in the framework and implement a exception list in PHPD 🤷‍♂️

2022-09-23 22:23 UTC, AJenbo commented
Maybe a better solution is to have a setting to ignore violations that are inherited?

2022-09-24 08:24 UTC, kylekatarnls commented
IIRC it's a `method_exists($class, 'toArray')` trick used from Laravel side, so no inheritence. I'm in favor of an unified `exceptions` option available in all the rules anyway.

2022-09-24 08:34 UTC, tvbeek commented
In this case I should remove the request because it isn't required to have. (I have changed it in my stubs)
If that wasn't possible I should add an unset call on the first line of the function to be clear that it isn't used. Another option is to add a suppress comment.

A generic rule means that you have more change to hide a place where it should notice about a problem.

2022-09-24 13:55 UTC, AJenbo commented
> IIRC it's a `method_exists($class, 'toArray')` trick used from Laravel side, so no inheritence. I'm in favor of an unified `exceptions` option available in all the rules anyway.

If that is the case then there is no reason to actually have the unused argument. PHP doesn't have argument overloading so if Laravel is calling the function with more arguments then it has it will still work the same.

2022-09-26 12:02 UTC, PedroPMS commented
As you guys said, there are other ways to suppress this warning, suppress comment, ignore inherited and others. The exception property is just one more option that anybody can use as they wish.  This feature has no breaking changes.

2022-10-19 00:08 UTC, Sandant589 commented
Ok

2023-08-20 18:47 UTC, kylekatarnls commented
Handling inheritance better does not prevent to have an list for exceptions.

This PR still need to have documentation update and unit tests. If so I would approve. @AJenbo @tvbeek @ravage84 Are you fine with that? Let's have a definitive go/no-go decision so either we define what it needs to be merged, or we close.

2023-08-21 16:36 UTC, ravage84 requested changes
Since it's pointless to fight bad framework design and people potentially shooting themselves in the foot, we can add this.

But it needs docs, tests etc as usual.

2026-05-10 02:13 UTC, AJenbo commented
Already implemented in https://github.com/phpmd/phpmd/pull/1277 ... well already merged I guess.

2026-05-10 02:13 UTC, closed without merging